### ISSUE TITLE
Doesn't work at Apple's arm64

### ISSUE THREAD

**Issue by catap** [sbt/ipcsocket#10]
Hey,

I'm playing for last couple of days with Apple's M1 that is arm64.

Right now sbt doesn't work because of missed JNA/JNI artifact on this project:
```
java.lang.UnsatisfiedLinkError: /Users/catap/Library/Caches/JNA/temp/jna12016497044725394171.tmp: dlopen(/Users/catap/Library/Caches/JNA/temp/jna12016497044725394171.tmp, 1): no suitable image found.  Did find:
	/Users/catap/Library/Caches/JNA/temp/jna12016497044725394171.tmp: no matching architecture in universal wrapper
	/Users/catap/Library/Caches/JNA/temp/jna12016497044725394171.tmp: no matching architecture in universal wrapper
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at org.scalasbt.ipcsocket.UnixDomainSocketLibrary.<clinit>(UnixDomainSocketLibrary.java:129)
	at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.socket(UnixDomainSocketLibrary.java:165)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:109)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:87)
	at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:342)
	at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:295)
	at sbt.xMain$.getSocketOrExit(Main.scala:118)
	at sbt.xMain$.run(Main.scala:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.UnsatisfiedLinkError: /Users/catap/Library/Caches/JNA/temp/jna12016497044725394171.tmp: dlopen(/Users/catap/Library/Caches/JNA/temp/jna12016497044725394171.tmp, 1): no suitable image found.  Did find:
	/Users/catap/Library/Caches/JNA/temp/jna12016497044725394171.tmp: no matching architecture in universal wrapper
	/Users/catap/Library/Caches/JNA/temp/jna12016497044725394171.tmp: no matching architecture in universal wrapper
```

I can build it on the machine, but I need your assistent to explain me how should I do it without sbt :)

Thanks!

**Comment by eed3si9n** [comment]
I'd suggest trying to downgrade sbt to 1.1.6 or 0.13.18 or something.

**Comment by catap** [comment]
@eed3si9n I afraid that downgrade to 0.13 isn't an option because scala3 requires something new :)

**Comment by eatkins** [comment]
It looks like jna is trying to support darwin arm64 but doesn't yet: https://github.com/java-native-access/jna/pull/1238

**Comment by catap** [comment]
It looks like JNI/JNA is stuck for a while: https://github.com/openjdk/aarch64-port/pull/3

:(
